flowchart TB
    subgraph ClientLayer[Client Layer]
        A[Client / App]
    end

    subgraph OrderSystem[Order System]
        B[Order API]
        C[Validation Layer]
        D[Business Logic]
        G[Status Control Service]
        H[Callback Dispatcher]
    end

    subgraph DataLayer[Data Layer]
        E[(MySQL DB)]
    end

    subgraph AsyncLayer[Async Layer]
        F[Scheduler / Job]
    end

    subgraph CallbackSystem[Callback System]
        I[Callback API]
    end

    A --> B
    B --> C
    C --> D
    D --> E
    E --> F
    F --> G
    G --> E
    G --> H
    H --> I
